This is the desktop version of my portfolio
Dinma-Faith/Mobile-View-Portfolio pull request #5
Opened 2022-03-25 18:13 UTC by Dinma-Faith

In this milestone  :+1: 
- I used HTML and CSS
- Added new images in it.

Comments and suggestions are welcomed
Thanks

2022-03-25 20:07 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Dinma-Faith👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 20:07 UTC, thecodechaser commented on index.html
> +            <div class="menu-content">
- [ ] You did a great job on the styles but for this project, you are supposed to stick to the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1 )template as much as possible. Please place some left, right margins on the header and use the correct color for the logo to make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/160192839-5dcbea46-a42d-4236-8f42-c5f13fae0878.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/160192863-483afa42-bfc5-4a28-ad2a-62dbfb7a6347.png)

2022-03-25 20:07 UTC, thecodechaser commented on index.html
>        <section class="intro">
- [ ] Please reduce the gap between social media icons and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/160193077-7fd59172-9995-4cec-a784-f3767d2025fa.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/160193117-c37cf6d7-3498-4079-be17-c37fafa16517.png)

2022-03-25 20:07 UTC, thecodechaser commented on index.html
> +              <button type="submit" class="btn">See Project</button>
- [ ] Please use the correct border color for all of your buttons to match the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/160193265-dec68908-0fe0-4548-bf19-4c2779ab5581.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/160193327-4c0548ff-40f3-4480-995f-6621b83774d0.png)

2022-03-25 20:07 UTC, thecodechaser commented on index.html
>      <section class="container-section2">
- [ ] Please use the correct right margin for this section to match the Figma design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/160193638-2559f76f-f759-47a4-9da7-57a0bd141a89.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/160193609-df65d141-814c-4c30-af27-29222d27e1f1.png)

2022-03-26 00:21 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️

Hi @Dinma-Faith,

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Suggested changes
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-26 00:21 UTC, AmaduKamara commented on style.css
> +  }
- [ ] Kindly adjust the spacing between each social media icon below as requested by the previous reviewer.
- Currently it's not displaying at around 768px - 1000px view. Please fix that 👍

** Your Design **
![image](https://user-images.githubusercontent.com/50941074/160216449-5657f31c-a7a6-473b-b8fd-eb3d3cba345a.png)

** The Figma Design **
![image](https://user-images.githubusercontent.com/50941074/160216482-007236bf-8a2b-4611-9a25-e60db97a3db4.png)

2022-03-26 00:21 UTC, AmaduKamara commented on style.css
> +  }
- [ ] Please fix the width of these sections to have `40%` on the left and `60%` on the right in order to match the design as previously asked by the first reviewer. 

** Your design **
![image](https://user-images.githubusercontent.com/50941074/160216769-a1d47509-a9c1-4d20-8bf4-fcfd1a36ed80.png)

** The Figma Design **
![image](https://user-images.githubusercontent.com/50941074/160216804-addbe9ca-70ae-41e3-8249-1dad84f9a68b.png)

2022-03-26 16:21 UTC, OLIPLICHE approved these changes
Hi @Dinma-Faith, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
- Please, go through your design again and make sure it looks like the one in Figma. This will make your portfolio more attractive and it might matter for future recruiters.

- The picture below is from Figma design. I drew the red lines to get your focus on this section.
kindly compare with your design from your browser and solve the issues. 
 
![d1](https://user-images.githubusercontent.com/63972670/160248284-077a9655-f52e-466a-80cf-b647397fbd10.JPG)

  
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-26 17:00 UTC, merged